rvm:
- 2.2

script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake

deploy:
  provider: heroku
  api_key:
    secure: Oata9VNZn/eYpCeR6U2tokj24sM6BbZRGOxQ6LeriO0QIBYBuVou7geZgvKOJYpIK1Azt1d7I606NoDpvzBAX84h3HWxn392F6P94l9DC2/L2F2YFLHG8PFBYPOGl8EYTQG7W2J4kT7Zpdaz9Gdi8XQKn66fpZQYFecpNAZdK/gSQfBQusvqjWkAPCXSS/FpIsN9t6/9O2LjdTKxkzWDEXTSNCY/bVHOT6353qt0FmFLlvmbOnTqwi7h/K+JQJpFZMmscRv3SrBa77bd64lPYDCWdEwim1kSLkBpvX0cWFCihpnnABqGuhBsigaq3tUOIEr+ciP13rJwWVl3Q/k+HlFg6PP5mbfdINdmU2/lL0m4cgTkxIcQvG3qh7BplOeM/hxzYqHYhhamky5u9HGzHYHOnxIO0IM0/gy7I1jEj224vsJTspUxYBgOkU2RgvKq8Kgwam4ZF+UQwj35wQB9Np2Eg2zmpf4Feue4Sq5Db9oD25dgiLY76AV8TPaqnRJhpfVOChRBShnl1EP10gM0KfOErv94LDJrM7x7+GjacNElmFkKSaBA/c2RCInkhX9luODk1EpDHZ5Mdz+T1h05hE9jnQincFcGa4pMg+SkHb0zYAvkwSmODjFazzypUECLDh8SKJZ+msLtJ93MkpEq3Ova7wofSp6cD/PGNnEHDGo=
  app: 'infinite-gorge-2302'
  on:
    repo: dobryakov/amy
    branch: master
  run:
    - "rake db:migrate"
    - "rake assets:precompile"
  strategy: git
